name: Lint & Format with Ruff

on: [ push, pull_request ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3
      - run: ruff check
      - run: ruff format --check --diff
